
CREATE USER LOG4ORA
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for LOG4ORA 
  GRANT CONNECT TO LOG4ORA;
  GRANT AQ_ADMINISTRATOR_ROLE TO LOG4ORA;
  GRANT AQ_USER_ROLE TO LOG4ORA;
  ALTER USER LOG4ORA DEFAULT ROLE ALL;
  -- 1 Tablespace Quota for LOG4ORA 
  ALTER USER LOG4ORA QUOTA UNLIMITED ON USERS;
  -- 3 Object Privileges for LOG4ORA 
  -- Note - needed direct grant on AQ packages for pl/sql code
  -- owned by log4ora to compile (role didn't work)
    GRANT EXECUTE ON SYS.DBMS_AQ TO LOG4ORA;
    GRANT EXECUTE ON SYS.DBMS_AQ_BQVIEW TO LOG4ORA;
    GRANT SELECT ON SYS.QT71312_BUFFER TO LOG4ORA;


